apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudprofile-frontend
  namespace: cloudprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudprofile-frontend
  template:
    metadata:
      labels:
        app: cloudprofile-frontend
    spec:
      containers:
        - name: frontend
          image: mohsinking2002/cloudprofile-frontend:1.1.2
          ports:
            - containerPort: 80
