apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudprofile-ingress
  namespace: cloudprofile
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: cloudprofile-redirect-https@kubernetescrd

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - cloudprofile.mohsin.asif-dev.site
      secretName: cloudprofile-tls

  rules:
    - host: cloudprofile.mohsin.asif-dev.site
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: cloudprofile-backend
                port:
                  number: 5001

          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: cloudprofile-frontend
                port:
                  number: 80
